name: Build/release

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12.8.0
      - name: install
        run: yarn
      - name: build # tsc, for a typescript project
        run: yarn build
      - name: test
        run: yarn test # ava, jest, whatever
      - name: release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        # ^ GITHUB_TOKEN is auto created by actions, but a bug was making github
        # actions use the _masked_ token as the token value in then env var.
        # to mitigate, i created a new github token called GH_TOKEN, &
        # loaded it into github > settings > secrets. electron-builder wants a
        # token name GH_TOKEN anyway :)
        run: yarn release # electron-builder --publish always
